joy_teleop:
  ros__parameters:

    drive:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 1.0
          offset: 0
        drive-steering_angle:
          axis: 2
          scale: 0.36
          offset: 0
        header-frame_id:
          value: 'base_link'

    power:
      type: topic
      interface_type: std_msgs/msg/Empty
      topic_name: power_trigger
      deadman_buttons: [8]

    turn_signal_left:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: turn_signal/left
      deadman_buttons: [4]
      message_value:
        data:
          value: true

    turn_signal_right:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: turn_signal/right
      deadman_buttons: [5]
      message_value:
        data:
          value: true